export default{
    path:'/mine',
    component:()=>import('@/views/mine'),
    children:[
        {
            path:'center',
            component:()=>import('@/views/mine/center.vue')
        },
        {
            path:'login',
            component:()=>import('@/components/login')
        },
        {
            path:'register',
            component:()=>import('@/components/register')
        },
        {
            path:'findPassword',
            component:()=>import('@/components/findPassword')
        }
        ,
        {
            path:'/mine',
            redirect:'center'
        }
    ]
}